project:
  type: book

book:
  title: "Survey Methodologies for Social Scientists"
  author: "Carey E. Stapleton & Stefani Langehennig"
  date: "24/07/2023"
  
  page-footer:
    left: |
      Survey Methodologies for Social Scientists (1e) was written by Carey E. Stapleton and Stefani Langehennig.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  chapters:
    - index.qmd
    - part: part_intro.qmd
      chapters:
      - ch01intro.qmd
      - ch00setup.qmd
      - ch02psych_response.qmd
      - ch03ethics.qmd
    - part: part_design.qmd
      chapters:
      - ch04q_design.qmd
      - ch05modes.qmd
      - ch06sampling.qmd
      - ch07weights.qmd
      - ch08measurement.qmd
    - part: part_analysis.qmd
      chapters:
      - ch09hyp_analysis_rep.qmd
      - ch10conclusion.qmd
      - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



