project:
  type: book

book:
  title: "Survey Methodologies for Social Scientists"
  author: "Carey E. Stapleton & Stefani Langehennig"
  date: "10/10/2022"
  
  page-footer:
    left: |
      Survey Methodologies for Social Scientists (1e) was written by Carey E. Stapleton and Stefani Langehennig.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  chapters:
    - index.qmd
    - ch01intro.qmd
    - ch02psych_response.qmd
    - ch03ethics.qmd
    - ch04q_design.qmd
    - ch05modes.qmd
    - ch06sampling.qmd
    - ch07weights.qmd
    - ch08measurement.qmd
    - ch09hyp_analysis_rep.qmd
    - ch10conclusion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



